### ISSUE TITLE
Order of items ruined if menu has to scroll 

### ISSUE THREAD

**Issue by prscX** [zawadz88/MaterialPopupMenu#14]
Hi @zawadz88,

This is with respect to [react-native-popover-menu: ISSUE 10](https://github.com/prscX/react-native-popover-menu/issues/10)

We have encountered below strange issues when the popover has scroll bar:
- Items are getting repeated
- Items order is getting mismatched

I have tried the same in example by adding more items, please find below output:

![issue](https://user-images.githubusercontent.com/28862892/37568130-ff4d68d0-2af6-11e8-8beb-42998164a3fa.gif)

Please let me know incase more information is required for the same.

Thanks
Pranav

**Comment by zawadz88** [comment]
Hi @prscX,
Thanks for reporting this. Weird bug indeed...

**Comment by zawadz88** [comment]
Hi @prscX,
This should be fixed in 1.4.1.
Again, thanks for reporting this!

**Comment by prscX** [comment]
Many Thanks @zawadz88 for the quick fix.

Thanks
Pranav
