### ISSUE TITLE
Feature: text color for each item

### ISSUE THREAD

**Issue by AlejandroHCruz** [zawadz88/MaterialPopupMenu#2]
Hi! 

Do you think it would be possible to add support for specifying the text color of each item?

I can also give it a look if you point me into the right direction to develop this feature 👍

**Comment by zawadz88** [comment]
Hi @AlejandroHCruz,
Sorry for not responding earlier.
I think this would be a very nice feature!
Off the top of my head you would probably need to pass that information into the item builder:
https://github.com/zawadz88/MaterialPopupMenu/blob/master/material-popup-menu/src/main/java/com/github/zawadz88/materialpopupmenu/MaterialPopupMenuBuilder.kt

and reference that later in https://github.com/zawadz88/MaterialPopupMenu/blob/master/material-popup-menu/src/main/java/com/github/zawadz88/materialpopupmenu/internal/PopupMenuAdapter.kt when binding items.
I was planning to add custom view support earlier but couldn't really find time to do it.

I'll try to come up with something soon though to add more styling/custom view options in the library :)

**Comment by zawadz88** [comment]
Hi @AlejandroHCruz,
Please let me know if the changes proposed in #4 are what you had in mind!

**Comment by AlejandroHCruz** [comment]
Hey @zawadz88  that's exactly what I had in mind, wow! Thanks a lot. This is now by far my favorite library for PopupMenus 🥇 
Adding support for custom views would be indeed very nice and bring the MaterialPopupMenu library into a whole new game level. Kudos for all the work so far!! 🔥🔥🔥🔥

**Comment by zawadz88** [comment]
Thanks for that feedback :)
The changes were merged to `master` and are available now with `1.1.0`.
