### ISSUE TITLE
.dismiss() method on popupMenu

### ISSUE THREAD

**Issue by cioccarellia** [zawadz88/MaterialPopupMenu#21]
it isn't possible to create a .dismiss() callback on the popupMenu? It would be nice to dismiss it programmatically or when the execution reaches the end of the callback

**Comment by zawadz88** [comment]
Hi @AndreaCioccarelli,
That sounds like a perfectly valid enhancement. I'll have a look :)

**Comment by zawadz88** [comment]
Hi @AndreaCioccarelli,
Are you happy with the changes proposed in #22? Or would you change anything/add something to that?

**Comment by cioccarellia** [comment]
Perfect like this, I'll let you know if I'll have some other ideas :)
