### ISSUE TITLE
How to show the menu anchored to the action overflow position?

### ISSUE THREAD

**Issue by jrcacd** [zawadz88/MaterialPopupMenu#23]

**Comment by zawadz88** [comment]
Hi,
Could you provide a bit more description?
A screenshot/code snippet would be very helpful.

**Comment by jrcacd** [comment]
What I need is to show the menu on the top right corner as your screenshot shows

https://github.com/zawadz88/MaterialPopupMenu/raw/master/art/sample_toolbar_dark.png

**Comment by zawadz88** [comment]
You can check out the sample app: https://github.com/zawadz88/MaterialPopupMenu/blob/master/sample/src/main/java/com/github/zawadz88/materialpopupmenu/sample/DarkActivity.kt#L49

**Comment by zawadz88** [comment]
The screenshot is actually taken from the sample app. Therefore closing this issue.

If you have further questions please don't hesitate to ask.

**Comment by ogasimli** [comment]
I am not able to position the popup menu below the view anchor like in this picture:

https://csharpcorner-mindcrackerinc.netdna-ssl.com/article/pop-up-menu-android-application/Images/image012.png

I have tried to set `dropdownGravity = Gravity.BOTTOM` without success. I have also tested other Gravity constants (i.e END, START, TOP, etc.) but wasn't able to achieve the desired result.
