### ISSUE TITLE
Menu resource file

### ISSUE THREAD

**Issue by d3bt3ch** [zawadz88/MaterialPopupMenu#24]
How can i use a menu resource file ?

**Comment by zawadz88** [comment]
Hi @debjitk,
The entire point of this library to simplify this and not use menus in XML. Therefore this feature is not supported.

If you want to use a menu file you can use a standard PopupMenu though.

**Comment by zawadz88** [comment]
If you want to use an XML file you can check this out: https://stackoverflow.com/a/21329225/973379

**Comment by d3bt3ch** [comment]
@zawadz88 My implementation is with PopupMenu but icons not showing up. Also, if i don't xml then in that case how can i use the library with java ?

**Comment by zawadz88** [comment]
Please see #7 although I would strongly recommend switching to Kotlin anyway.

**Comment by d3bt3ch** [comment]
@zawadz88 We would eventually. For the moment the app is already been built using java.
