### ISSUE TITLE
Migrate Support Library dependencies to Jetpack

### ISSUE THREAD

**Issue by zawadz88** [zawadz88/MaterialPopupMenu#31]
As Android Support libraries are being replaced by AndroidX (which is now stable), this library's dependencies should be updated as well.

https://developer.android.com/topic/libraries/support-library/androidx-overview

This will introduce breaking changes so a major version name update will be required.

**Comment by zawadz88** [comment]
Done on https://github.com/zawadz88/MaterialPopupMenu/tree/feature/issue-31-android-x-support
Waiting for Butterknife 9.0.0 to reach stable for now.

**Comment by jrcacd** [comment]
Waiting for this to use

**Comment by zawadz88** [comment]
Released in 3.0.0
