### ISSUE TITLE
How to add an disabled menu entry?

### ISSUE THREAD

**Issue by jrcacd** [zawadz88/MaterialPopupMenu#33]
We need that some menu entries be visible, but be disabled because some users do not have sufficient permissions.

**Comment by zawadz88** [comment]
Hi,
how would those disabled items look and behave?

**Comment by jrcacd** [comment]
Perhaps have an grayed icon and not execute the callback code.

**Comment by zawadz88** [comment]
So clicking on such an item would also not dismiss the popup window?

Regarding the UI of a disabled item it's possible by using an item with a custom layout. As far as the on-click behaviour is concerned, this might a bit more tricky. I'd probably try to disable the item in `viewBoundCallback` and see if that works.

**Comment by zawadz88** [comment]
You could have the following:
```
val popupMenu = popupMenu {
            section {
                // ...
                customItem {
                    layoutResId = R.layout.you_disabled_item_layout
                    viewBoundCallback = { view ->
                        view.isEnabled = false
                    }
                }
            }
        }

        popupMenu.show(context, view)
```

Adding `view.isEnabled = false` should be enough to disable onClick events.

**Comment by jrcacd** [comment]
Umm, ok, but a litle tricky
