### ISSUE TITLE
Logo Contribution

### ISSUE THREAD

**Issue by ghostofiht** [zawadz88/MaterialPopupMenu#48]
Hi, I'm a logo designer. I support open source projects with my logo designs. I would also like to make a contribution to the MaterialPopupMenu project. I have a great design idea. You want to see this?

**Comment by zawadz88** [comment]
Hi @ghostofiht,
Sure!

**Comment by ghostofiht** [comment]
Please feel free to tell me if there is something you want to change in design.  I applied multiple colors. You can pick someone you like. Or you can ask me to apply a different color. I'm happy to contribute to the open-source community.


![material_poup_menu_re](https://user-images.githubusercontent.com/42060713/56149510-66355000-5fb5-11e9-9298-1ade3475da40.jpg)

**Comment by zawadz88** [comment]
I like the first one the most :) Could you submit a PR replacing the one at https://github.com/zawadz88/MaterialPopupMenu/blob/master/art/components_menus.png with the one on the right? If you have the one the left in 512x512 than I could use it to replace the app launcher icons for the sample as well (the ones in `mipmap-xxx` e.g. https://github.com/zawadz88/MaterialPopupMenu/tree/master/sample/src/main/res/mipmap-mdpi)

Thanks for contributing!

**Comment by ghostofiht** [comment]
I've added application icons. I've also included other formats that may be required. I sent a PR. https://github.com/zawadz88/MaterialPopupMenu/pull/50 

Please feel free to tell us if you need logo for your other projects.

Good jobs !

**Comment by zawadz88** [comment]
Merged to `master`, thanks!
