### ISSUE TITLE
any similar iOS compatible library?

### ISSUE THREAD

**Issue by prscX** [zawadz88/MaterialPopupMenu#5]
Hi @zawadz88 

First of all I would like to appreciate for open sourcing such a nice library.

Do you any similar library for iOS platform as well?

Thanks
Pranav

**Comment by zawadz88** [comment]
Hi @prscX,
Thank you for your kind words :)
I don't really know anything about an iOS equivalent of this library, however I'm not doing any iOS work these days so I'm probably not the best guy to ask...

**Comment by prscX** [comment]
Thanks @zawadz88 for the response.

Thanks
Pranav
