### ISSUE TITLE
Is it possible to open the menu in the center of the screen? Or set horizontal margins?

### ISSUE THREAD

**Issue by Jaguarhl** [zawadz88/MaterialPopupMenu#58]
I need to open the menu centered horizontally.  I can't find a way.

**Comment by zawadz88** [comment]
Hi,
I don't think it is possible to center it the way you described (at least I don't see an easy way to do this).
Offsets are possible - there's an example in the sample app.

What you're describing seems more like a dialog to me, are you sure you want to use this library for this?
