### ISSUE TITLE
Anchoring the popup left bottom of the button

### ISSUE THREAD

**Issue by egkz** [zawadz88/MaterialPopupMenu#60]

**Comment by zawadz88** [comment]
Hi @egek92,
It is possible to offset the popup by a specified amount. Please see the "Custom offsets" in the sample app.
You need to create your own popup style with `android:dropDownVerticalOffset` and `android:dropDownHorizontalOffset` provided.

**Comment by egek92** [comment]
is it possible to have this shape as popup https://imgur.com/a/68WJFlV ? because otherwise the popup dims the button too

**Comment by zawadz88** [comment]
You can change a popup background to any shape you choose. There's an example on how to do that in the sample app where a background with more rounded corners is used.
