### ISSUE TITLE
How to using API's in Java?

### ISSUE THREAD

**Issue by prscX** [zawadz88/MaterialPopupMenu#7]
Hi @zawadz88 

I am trying to using API's in Java, but I am getting error while adding item to section holder. Please find below snippet of the same:

```java
ItemHolder item = new ItemHolder();
    item.setLabel("Item 1");

    SectionHolder section = new SectionHolder();
    section.setTitle("Section");

    section.item(item);
```

It is giving me below exception at last line:

<img width="1107" alt="screen shot 2018-01-31 at 6 14 52 pm" src="https://user-images.githubusercontent.com/28862892/35623778-ce4df226-06b2-11e8-9e44-733501600dc7.png">

Can you please guide me on how to add a item to section

Thanks
Pranav

**Comment by prscX** [comment]
Hi @zawadz88, I got it working.

Thanks
Pranav

**Comment by Soptq** [comment]
@prscX Could you share how to use it in Java? I'm a student learning java so I'm not so familiar with Kotlin. Thanks very much.

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Xperia Z5 dual 发送_

**Comment by Soptq** [comment]
Hi @prscX , Could you please share how to use it in Java? I'm a student learning java so I'm not so familiar with Kotlin. Thanks very much.

**Comment by prscX** [comment]
Hi @Soptq,

Please refer below class file `Show` method for the bridging between Java and Kotlin:

https://github.com/prscX/react-native-popover-menu/blob/master/android/src/main/java/ui/popovermenu/RNPopoverMenuModule.java

Let me know in case you need any help.

Thanks
Pranav

**Comment by Soptq** [comment]
@prscX I got it! I really enjoy your concise code, mine is always a mess.:smile:


**Thanks very much!**
